packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@electric-sql/pglite@0.5.6'

onlyBuiltDependencies:
  - "@electric-sql/pglite"
  - "sharp"
