"""Loopback-only owner review. No publishing credentials enter the browser."""
import base64
import hmac
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import json
import mimetypes
from pathlib import Path
import secrets
import sqlite3
from urllib.parse import urlsplit, parse_qs

from engine import EngineError, FIELD_GROUPS, LIST_FIELDS, REQUIRED, Workspace, atomic_write, identifier, require


class AccessError(EngineError):
    def __init__(self, message, status):
        super().__init__(message)
        self.status = status


def server_for(workspace, brand, port=0, token=None):
    identifier(brand)
    check = Workspace(workspace)
    check.close()
    token = token or secrets.token_urlsafe(32)
    assets = Path(__file__).resolve().parents[1] / "assets"

    class Handler(BaseHTTPRequestHandler):
        def setup(self):
            super().setup()
            self.connection.settimeout(15)

        def log_message(self, *args):
            pass

        def reply(self, status, body, mime="application/json"):
            raw = body if isinstance(body, bytes) else json.dumps(body, ensure_ascii=False).encode()
            self.send_response(status)
            self.send_header("Content-Type", mime)
            self.send_header("Content-Length", str(len(raw)))
            self.send_header("Cache-Control", "no-store")
            self.send_header("X-Content-Type-Options", "nosniff")
            self.send_header("Referrer-Policy", "no-referrer")
            self.send_header("Content-Security-Policy", "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' blob:; media-src 'self' blob:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'")
            self.end_headers()
            self.wfile.write(raw)

        def allowed(self, private=True):
            host = f"127.0.0.1:{self.server.server_port}"
            if self.headers.get("Host") != host:
                raise AccessError("Invalid dashboard host.", 403)
            origin = self.headers.get("Origin")
            if origin is not None and origin != "http://" + host:
                raise AccessError("Cross-origin access is not allowed.", 403)
            if self.headers.get("Sec-Fetch-Site") == "cross-site":
                raise AccessError("Cross-site request blocked.", 403)
            if private:
                supplied = self.headers.get("Authorization", "")
                if not hmac.compare_digest(supplied.encode("utf-8"), ("Bearer " + token).encode("utf-8")):
                    raise AccessError("Open the dashboard link generated by the local command.", 401)

        def do_GET(self):
            ws = None
            try:
                route = urlsplit(self.path)
                public = {"/": "dashboard.html", "/dashboard.js": "dashboard.js", "/dashboard.css": "dashboard.css"}
                self.allowed(private=route.path not in public)
                if route.path in public:
                    path = assets / public[route.path]
                    return self.reply(200, path.read_bytes(), (mimetypes.guess_type(path)[0] or "text/plain") + "; charset=utf-8")
                ws = Workspace(workspace)
                if route.path == "/api/state":
                    return self.reply(200, {**ws.snapshot(brand), "questionnaire": FIELD_GROUPS, "list_fields": sorted(LIST_FIELDS), "required": sorted(REQUIRED)})
                if route.path == "/api/asset":
                    key = parse_qs(route.query).get("id", [""])[0]
                    asset, raw = ws.asset_bytes(brand, key)
                    ext = Path(asset["path"]).suffix
                    require(ext in {".png", ".jpg", ".jpeg", ".webp", ".mp4", ".webm", ".mp3", ".wav"}, "This asset is available locally but cannot be previewed inline.")
                    return self.reply(200, raw, mimetypes.guess_type(asset["path"])[0] or "application/octet-stream")
                self.reply(404, {"error": "Not found"})
            except (EngineError, OSError, ValueError, sqlite3.Error) as exc:
                self.reply(getattr(exc, "status", 400), {"error": str(exc) if isinstance(exc, EngineError) else "Unable to read this workspace resource."})
            finally:
                if ws: ws.close()

        def do_POST(self):
            ws = None
            try:
                self.allowed()
                require(self.headers.get("Content-Type") == "application/json", "Use JSON requests.")
                size = int(self.headers.get("Content-Length", "0"))
                require(0 < size <= 30 * 1024 * 1024, "Request exceeds 30 MB.")
                value = json.loads(self.rfile.read(size))
                require(isinstance(value, dict), "Expected a JSON object.")
                ws = Workspace(workspace)
                route = urlsplit(self.path).path
                actor = value.get("actor")
                if route == "/api/brand": result = ws.update_brand(brand, value["answers"], actor)
                elif route == "/api/brand-approve": result = ws.approve_brand(brand, value["hash"], actor)
                elif route == "/api/item-approve": result = ws.approve_item(brand, value["id"], value["hash"], actor)
                elif route == "/api/feedback": result = ws.feedback(brand, value)
                elif route == "/api/rule-approve": result = ws.approve_rule(brand, value["id"], actor)
                elif route == "/api/rule-retire": result = ws.retire_rule(brand, value["id"], actor)
                elif route == "/api/export": result = ws.export_item(brand, value["id"])
                elif route == "/api/asset":
                    require(isinstance(value.get("name"), str) and Path(value["name"]).name == value["name"], "Invalid upload filename.")
                    raw = base64.b64decode(value["base64"], validate=True)
                    upload = ws.safe_path("incoming/" + secrets.token_hex(12) + Path(value["name"]).suffix.lower())
                    atomic_write(upload, raw)
                    try: result = ws.import_asset(brand, str(upload), value["role"], value["rights"], value["note"], actor, display_name=value["name"])
                    finally: upload.unlink(missing_ok=True)
                else:
                    return self.reply(404, {"error": "Not found"})
                self.reply(200, result)
            except (EngineError, OSError, ValueError, KeyError, TypeError, sqlite3.Error) as exc:
                self.reply(getattr(exc, "status", 400), {"error": str(exc) if isinstance(exc, EngineError) else "Could not save. Check the fields and file size."})
            finally:
                if ws: ws.close()

    server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    return server, token


def serve(workspace, brand, port):
    server, token = server_for(workspace, brand, port)
    print(f"Owner dashboard: http://127.0.0.1:{server.server_port}/#{token}", flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
