import { Activity, CheckCircle2, Clock3, Fingerprint, Workflow } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { EmptyState, Panel } from "@/components/panel";
import { StatusBadge } from "@/components/status-badge";
import { listRuns } from "@/lib/data";
import { formatDateTime, humanize } from "@/lib/format";

export const metadata = { title: "Workflow runs" };

export default async function RunsPage() {
  const runs = await listRuns();
  return (
    <>
      <PageHeader eyebrow="Durable workflows" title="Every run has a trace." description="Agent work is modeled as restartable, idempotent steps. Failures remain inspectable and ambiguous provider responses require reconciliation." />
      <div className="run-summary">
        <div><Activity size={17} /><span><strong>{runs.length}</strong> recent runs</span></div>
        <div><CheckCircle2 size={17} /><span><strong>{runs.filter((run) => run.status === "SUCCEEDED").length}</strong> succeeded</span></div>
        <div><Clock3 size={17} /><span><strong>{runs.filter((run) => ["PENDING", "RUNNING", "WAITING_FOR_APPROVAL", "WAITING_FOR_RETRY"].includes(run.status)).length}</strong> active or waiting</span></div>
      </div>
      <Panel title="Execution ledger" description="Newest workflow first · durable database state">
        {runs.length ? <div className="calendar-table-wrap"><table className="data-table runs-table"><thead><tr><th>Workflow</th><th>Status</th><th>Current step</th><th>Created</th><th>Trace</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td><div className="run-name"><span><Workflow size={16} /></span><div><strong>{humanize(run.type)}</strong><small>{run.id}</small></div></div></td><td><StatusBadge value={run.status} /></td><td>{humanize(run.currentStep)}</td><td>{formatDateTime(run.createdAt)}</td><td><code className="trace-code"><Fingerprint size={13} />{run.traceId.slice(0, 8)}…</code></td></tr>)}</tbody></table></div> : <EmptyState title="No workflows have run" body="The durable ledger will populate when strategy, generation, QA, publishing, or analytics workflows are enqueued." />}
      </Panel>
      <p className="runs-footnote">The empty state is valid: imported legacy content does not pretend it was generated by a workflow that never ran.</p>
    </>
  );
}
